create database lms character set utf8;
use lms;

source /home/MySQLData/lms_accountpo.sql;
source /home/MySQLData/lms_arrival.sql;
source /home/MySQLData/lms_accountpo.sql;
source /home/MySQLData/lms_citypo.sql;
source	  /home/MySQLData/lms_driverpo.sql;
source	  /home/MySQLData/lms_loadcarpo.sql;
source	  /home/MySQLData/lms_paymentpo.sql;
source	  /home/MySQLData/lms_receivepo.sql;
source	  /home/MySQLData/lms_vehiclepo.sql;
source /home/MySQLData/lms_arrivalpo.sql;
source  /home/MySQLData/lms_commoditypo.sql;
 source  /home/MySQLData/lms_earningspo.sql;
source   /home/MySQLData/lms_loadpo.sql;
source   /home/MySQLData/lms_personnelpo.sql;
source   /home/MySQLData/lms_salarystrategypo.sql;
source   /home/MySQLData/lms_warehousepo.sql;
source /home/MySQLData/lms_checkinpo.sql ;
source  /home/MySQLData/lms_departmentpo.sql;
source  /home/MySQLData/lms_initialinforpo.sql;
source  /home/MySQLData/lms_numoccupancypo.sql;
source  /home/MySQLData/lms_pricestrategypo.sql ;
source  /home/MySQLData/lms_sendpo.sql;
source /home/MySQLData/lms_checkoutpo.sql ;
source /home/MySQLData/lms_dispatchpo.sql	  ;
source /home/MySQLData/lms_inventorypo.sql	;
source /home/MySQLData/lms_operationpo.sql	;
source /home/MySQLData/lms_receiptpo.sql	 ; 
source /home/MySQLData/lms_userpo.sql;