create table lms set character = utf8;
use lms;

source lms_accountpo.sql;
source lms_arrival.sql;
source lms_accountpo.sql;
source lms_citypo.sql;
source	  lms_driverpo.sql;
source	  lms_loadcarpo.sql;
source	  lms_paymentpo.sql;
source	  lms_receivepo.sql;
source	  lms_vehiclepo.sql;
source lms_arrivalpo.sql;
source  lms_commoditypo.sql;
 source  lms_earningspo.sql;
source   lms_loadpo.sql;
source   lms_personnelpo.sql;
source   lms_salarystrategypo.sql;
source   lms_warehousepo.sql;
source lms_checkinpo.sql ;
source  lms_departmentpo.sql;
source  lms_initialinforpo.sql;
source  lms_numoccupancypo.sql;
source  lms_pricestrategypo.sql ;
source  lms_sendpo.sql;
source lms_checkoutpo.sql ;
source lms_dispatchpo.sql	  ;
source lms_inventorypo.sql	;
source lms_operationpo.sql	;
source lms_receiptpo.sql	 ; 
source lms_userpo.sql;